[2024-12-21T21:58:02.594+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T21:57:00+00:00 [queued]>
[2024-12-21T21:58:02.601+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T21:57:00+00:00 [queued]>
[2024-12-21T21:58:02.601+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T21:58:02.602+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T21:58:02.602+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T21:58:02.612+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): commit_and_push_task> on 2024-12-21 21:57:00+00:00
[2024-12-21T21:58:02.614+0000] {standard_task_runner.py:55} INFO - Started process 9919 to run task
[2024-12-21T21:58:02.617+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'commiteando_cosas', 'commit_and_push_task', 'scheduled__2024-12-21T21:57:00+00:00', '--job-id', '2724', '--raw', '--subdir', 'DAGS_FOLDER/elPataCommits.py', '--cfg-path', '/tmp/tmp2__rycvb']
[2024-12-21T21:58:02.618+0000] {standard_task_runner.py:83} INFO - Job 2724: Subtask commit_and_push_task
[2024-12-21T21:58:02.666+0000] {task_command.py:376} INFO - Running <TaskInstance: commiteando_cosas.commit_and_push_task scheduled__2024-12-21T21:57:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T21:58:02.720+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=commiteando_cosas
AIRFLOW_CTX_TASK_ID=commit_and_push_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-21T21:57:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-21T21:57:00+00:00
[2024-12-21T21:58:02.721+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-21T21:58:02.721+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        git add . &&\n        git commit -m "Commit diario: $(date \'+%Y-%m\')" &&\n        git push origin main\n        ']
[2024-12-21T21:58:02.728+0000] {subprocess.py:86} INFO - Output:
[2024-12-21T21:58:02.732+0000] {subprocess.py:93} INFO - fatal: not a git repository (or any of the parent directories): .git
[2024-12-21T21:58:02.733+0000] {subprocess.py:97} INFO - Command exited with return code 128
[2024-12-21T21:58:02.741+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2024-12-21T21:58:02.744+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=commiteando_cosas, task_id=commit_and_push_task, execution_date=20241221T215700, start_date=20241221T215802, end_date=20241221T215802
[2024-12-21T21:58:02.754+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2724 for task commit_and_push_task (Bash command failed. The command returned a non-zero exit code 128.; 9919)
[2024-12-21T21:58:02.800+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T21:58:02.821+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
