[2024-12-21T20:25:07.323+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 6.1-monitoreando.tarea2 scheduled__2022-06-28T00:00:00+00:00 [queued]>
[2024-12-21T20:25:07.410+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 6.1-monitoreando.tarea2 scheduled__2022-06-28T00:00:00+00:00 [queued]>
[2024-12-21T20:25:07.415+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T20:25:07.418+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T20:25:07.419+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T20:25:07.685+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): tarea2> on 2022-06-28 00:00:00+00:00
[2024-12-21T20:25:07.706+0000] {standard_task_runner.py:55} INFO - Started process 4361 to run task
[2024-12-21T20:25:07.732+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoreando', 'tarea2', 'scheduled__2022-06-28T00:00:00+00:00', '--job-id', '2326', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmp8lhre2fm']
[2024-12-21T20:25:07.748+0000] {standard_task_runner.py:83} INFO - Job 2326: Subtask tarea2
[2024-12-21T20:25:08.117+0000] {task_command.py:376} INFO - Running <TaskInstance: 6.1-monitoreando.tarea2 scheduled__2022-06-28T00:00:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T20:25:08.651+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=6.1-monitoreando
AIRFLOW_CTX_TASK_ID=tarea2
AIRFLOW_CTX_EXECUTION_DATE=2022-06-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-28T00:00:00+00:00
[2024-12-21T20:25:08.672+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-21T20:25:08.682+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Tarea 2"]
[2024-12-21T20:25:08.714+0000] {subprocess.py:86} INFO - Output:
[2024-12-21T20:25:08.723+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2024-12-21T20:25:08.725+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2024-12-21T20:25:08.731+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-21T20:25:08.773+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-21T20:25:08.784+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=6.1-monitoreando, task_id=tarea2, execution_date=20220628T000000, start_date=20241221T202507, end_date=20241221T202508
[2024-12-21T20:25:08.856+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2326 for task tarea2 (Bash command failed. The command returned a non-zero exit code 2.; 4361)
[2024-12-21T20:25:08.951+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T20:25:09.666+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
