[2024-12-21T20:25:04.655+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 6.1-monitoreando.tarea2 scheduled__2022-06-25T00:00:00+00:00 [queued]>
[2024-12-21T20:25:04.698+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 6.1-monitoreando.tarea2 scheduled__2022-06-25T00:00:00+00:00 [queued]>
[2024-12-21T20:25:04.704+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T20:25:04.714+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-21T20:25:04.717+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-21T20:25:04.911+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): tarea2> on 2022-06-25 00:00:00+00:00
[2024-12-21T20:25:04.952+0000] {standard_task_runner.py:55} INFO - Started process 4352 to run task
[2024-12-21T20:25:04.990+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoreando', 'tarea2', 'scheduled__2022-06-25T00:00:00+00:00', '--job-id', '2325', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpmlysejr8']
[2024-12-21T20:25:04.998+0000] {standard_task_runner.py:83} INFO - Job 2325: Subtask tarea2
[2024-12-21T20:25:05.514+0000] {task_command.py:376} INFO - Running <TaskInstance: 6.1-monitoreando.tarea2 scheduled__2022-06-25T00:00:00+00:00 [running]> on host a39b43f32cb0
[2024-12-21T20:25:07.308+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=6.1-monitoreando
AIRFLOW_CTX_TASK_ID=tarea2
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T00:00:00+00:00
[2024-12-21T20:25:07.335+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-21T20:25:07.370+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Tarea 2"]
[2024-12-21T20:25:07.531+0000] {subprocess.py:86} INFO - Output:
[2024-12-21T20:25:07.581+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2024-12-21T20:25:07.598+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2024-12-21T20:25:07.610+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-21T20:25:07.788+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-21T20:25:07.868+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=6.1-monitoreando, task_id=tarea2, execution_date=20220625T000000, start_date=20241221T202504, end_date=20241221T202507
[2024-12-21T20:25:08.007+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2325 for task tarea2 (Bash command failed. The command returned a non-zero exit code 2.; 4352)
[2024-12-21T20:25:08.144+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-21T20:25:08.797+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
